# Generated by Django 6.0.4 on 2026-08-10 16:03

import apps.shared.files_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_customer_address_customer_credit_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="legal_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shop",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.shared.files_utils.file_upload_path,
                validators=[apps.shared.files_utils.FileSizeValidator(1048576)],
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="tax_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
