# Generated by Django 6.0.4 on 2026-08-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_shop_legal_name_shop_logo_shop_tax_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-created_at"]},
        ),
    ]
