# Generated by Django 6.0.4 on 2026-08-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_alter_customer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="block_over_credit_limit",
            field=models.BooleanField(default=False),
        ),
    ]
