"""Shared PDF rendering for statement/report exports (apps.ledger). One
helper so every export shares the same look — title, meta block, one table,
optional summary lines — instead of each view hand-rolling reportlab
flowables. Built on reportlab (pure-Python wheel, no system libs needed),
not an HTML-to-PDF engine, so there's no template layer to keep in sync."""

from io import BytesIO

from django.http import HttpResponse
from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

_STYLES = getSampleStyleSheet()
_TITLE_STYLE = ParagraphStyle(
    "UdharoTitle", parent=_STYLES["Title"], fontSize=16, spaceAfter=4
)
_META_STYLE = ParagraphStyle(
    "UdharoMeta",
    parent=_STYLES["Normal"],
    fontSize=9,
    textColor=colors.HexColor("#444444"),
)
_SUMMARY_STYLE = ParagraphStyle("UdharoSummary", parent=_STYLES["Normal"], fontSize=10)
_FOOTER_STYLE = ParagraphStyle(
    "UdharoFooter", parent=_STYLES["Normal"], fontSize=7.5, textColor=colors.grey
)


def render_pdf_response(
    *,
    filename,
    title,
    meta_lines,
    table_head,
    table_rows,
    summary_lines=None,
    col_widths=None,
):
    """Builds a simple ledger-style PDF and returns it as a downloadable
    HttpResponse.

    - meta_lines: plain strings shown under the title (shop/customer info).
    - table_head / table_rows: the one table this document is built around.
    - summary_lines: optional [(label, value), ...] totals shown below it.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
    )

    elements = [Paragraph(title, _TITLE_STYLE)]
    for line in meta_lines:
        elements.append(Paragraph(line, _META_STYLE))
    elements.append(Spacer(1, 10))

    table = Table([table_head] + table_rows, colWidths=col_widths, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
                (
                    "ROWBACKGROUNDS",
                    (0, 1),
                    (-1, -1),
                    [colors.white, colors.HexColor("#f7f7f7")],
                ),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    elements.append(table)

    if summary_lines:
        elements.append(Spacer(1, 12))
        for label, value in summary_lines:
            elements.append(Paragraph(f"<b>{label}:</b> {value}", _SUMMARY_STYLE))

    elements.append(Spacer(1, 14))
    elements.append(
        Paragraph(
            f"Generated by Udharo Tracker on {timezone.now().strftime('%Y-%m-%d %H:%M')}",
            _FOOTER_STYLE,
        )
    )

    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()

    response = HttpResponse(pdf_bytes, content_type="application/pdf")
    response["Content-Disposition"] = f'attachment; filename="{filename}"'
    return response
