# Generated by Django 6.0.4 on 2026-08-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_creditscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderlog',
            name='channel',
            field=models.CharField(choices=[('note', 'Note'), ('sms', 'SMS'), ('auto', 'Automatic')], default='note', max_length=10),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
