# Generated by Django 6.0.4 on 2026-08-05 15:58

import apps.shared.files_utils
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_transaction_transactioncounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("fonepay", "Fonepay"),
                    ("nepal_pay", "Nepal Pay"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Bank/wallet transaction ID, cheque number, etc.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="PaymentPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.shared.files_utils.file_upload_path,
                        validators=[apps.shared.files_utils.FileSizeValidator(5242880)],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="ledger.payment",
                    ),
                ),
            ],
        ),
    ]
