# Generated by Django 6.0.4 on 2026-08-05 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_payment_payment_mode_payment_reference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "debt_transaction",
                    models.ForeignKey(
                        limit_choices_to={"txn_type__in": ["opening", "udharo"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations_received",
                        to="ledger.transaction",
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        limit_choices_to={"txn_type": "payment"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations_made",
                        to="ledger.transaction",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="allocation_amount_positive",
                    )
                ],
            },
        ),
    ]
