# Generated by Django 6.0.4 on 2026-08-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0006_allocation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="udharoentry",
            options={"ordering": ["-created_at"]},
        ),
    ]
