# Generated by Django 6.0.4 on 2026-08-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0007_alter_payment_options_alter_udharoentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_voided",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="void_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="udharoentry",
            name="is_voided",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="udharoentry",
            name="void_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="udharoentry",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
