# Generated by Django 6.0.4 on 2026-08-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0008_payment_is_voided_payment_void_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminderlog",
            name="channel",
            field=models.CharField(
                choices=[
                    ("note", "Note"),
                    ("sms", "SMS"),
                    ("whatsapp", "WhatsApp"),
                    ("auto", "Automatic"),
                ],
                default="note",
                max_length=10,
            ),
        ),
    ]
